### ISSUE TITLE
显示的标签样式有些对不齐

### ISSUE THREAD

**Issue by Atomseek** [lyzoris/BilibiliComments-userTag#2]
我把第56行的样式改成这样就好点了：
.adblock-tips{display:none!important}.userTag{display:inline-block;position:relative;text-align:center;border-width:0px;vertical-align:sub;margin-left:4px;margin-right:4px;cursor:default;bottom: -2px}.tag-name{position: relative;border-color:rgba(169,195,233,0.1803921568627451);color:rgba(87,127,184,1);background-color:#9ebae833;float:left;text-align:center;border-width:0.5px;border-style:solid;border-bottom-left-radius:1px;border-top-left-radius:1px;height:16px;line-height:16px}.tag-class{position:relative;border-bottom-right-radius:1px;border-top-right-radius:1px;float:left;box-sizing:content-box;text-align:center;border-width:0.5px;border-color:#f25d8e;border-style:solid;border-bottom-left-radius:1px;border-top-left-radius:1px;color:#f25d8e;height:16px;line-height:16px}.tag-font{position: relative;font-weight:400}

**Comment by lyzoris** [comment]
贴的样式中好像就增加了 userTag 的 bottom: -2px ，我能理解为是标签与文字上下对不齐嘛，我这边网页显示正常，能否截图展示一下呢。

**Comment by Atomseek** [comment]
userTag 的 bottom: -2px是我觉得跟评论ID有点有点不均衡加的，另外就是把tag-name设为相对定位，删掉了一些样式，让文字能够居中了，原本文字不是居中的。
![Screenshot_20230620_130459](https://github.com/lyzoris/Bilibili-UserComponentTag/assets/67729048/6dc8a860-28d4-4cc1-8539-2385d4c682ec)
![Screenshot_20230620_131328](https://github.com/lyzoris/Bilibili-UserComponentTag/assets/67729048/2d46ffab-8b9b-4949-b0ba-f73cc78208c7)

**Comment by lyzoris** [comment]
接下来会将标签内改成flex布局，文字应该是居中的，至于标签错位我这里是对齐的：
![image](https://github.com/lyzoris/Bilibili-UserComponentTag/assets/75029228/24cdae66-6d71-4431-a646-1c59defde16d)
可以尝试一下这个样式：  
` .tag-name {
        border-color: rgba(169, 195, 233, 0.1803921568627451);
        color: rgba(87, 127, 184, 1);
        background-color: #9ebae833;
        float: left;
        display: flex;
        flex-wrap: wrap;
        align-content: center;
        justify-content: center;
        border-width: 0.5px;
        border-style: solid;
        border-bottom-left-radius: 1px;
        border-top-left-radius: 1px;
        height: 16px;
    }
    
    .tag-class {
        position: relative;
        border-bottom-right-radius: 1px;
        border-top-right-radius: 1px;
        float: left;
        display: flex;
        flex-wrap: wrap;
        align-content: center;
        justify-content: center;
        box-sizing: content-box;
        border-width: 0.5px;
        border-color: #f25d8e;
        border-style: solid;
        border-bottom-left-radius: 1px;
        border-top-left-radius: 1px;
        color: #f25d8e;
        height: 16px;
    }
    
    .tag-font {
        font-weight: 400;
        font-size: 10px;
    }`

**Comment by Atomseek** [comment]
也许是我开了某些样式插件的影响，期待更新
